# Generated by Django 5.2.6 on 2025-11-12 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='to_Do',
            new_name='Tasks',
        ),
    ]
