# Generated by Django 5.2.6 on 2025-11-14 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tasks_notes_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steps',
            old_name='decription',
            new_name='description',
        ),
    ]
